services:
  node:
    build:
      dockerfile: ./.docker/node.dockerfile
      context: .
      ssh:
        - default
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    ports:
      - "${HOST}:${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
    networks:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  test:
    build:
      context: .
      dockerfile: ./.docker/test.dockerfile
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
    #      - ~/.ssh:/root/.ssh:ro
    networks:
      - redis
      - mysql
  #    environment:
  #      -NPM_TOKEN: ${NPM_TOKEN}
  mysql:
    image: mariadb:10.5
    ports:
      - ${MYSQL_PORT}
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - mysql
  redis:
    image: redis
    networks:
      - redis
    ports:
      - ${REDIS_PORT}
    command: redis-server --port ${REDIS_PORT}
networks:
  mysql:
  redis:
    driver: bridge